#!/bin/bash

USUARIO=$(who | awk '{print $1}')
export USUARIO

cp /usr/share/applications/signer-desktop.desktop /home/$USUARIO/Desktop/signer-desktop.desktop

# x=$(su -c "/opt/demoiselle/tool/signer-agent-desktop/signerDesktopAgent.sh &" -s /bin/bash $USUARIO);

JAVA_OPTS="-Xms128m -Xmx1024m -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40"
export JAVA_OPTS

su -c "nohup java $JAVA_OPTS -jar /opt/demoiselle/tool/signer-agent-desktop/lib/agent-desktop-3.0.0-SNAPSHOT.jar &" -s /bin/bash $USUARIO

exit 0